/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package asociaciones.pantallas;

import asociaciones.entidades.Curso;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Kelvin
 */
public class PantallaGestorCursos extends javax.swing.JFrame {

    /**
     * Creates new form PantallaGestorCuross
     */
    public PantallaGestorCursos(List<Curso> lista) {
        initComponents();
        this.ListaCurso = lista;
        llenarList();
        this.setLocationRelativeTo(null);

    }
    public static List<Curso> ListaCurso= new ArrayList<Curso>();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_salir1 = new javax.swing.JButton();
        btn_agregar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_cursos = new javax.swing.JList<>();
        btn_verProfesor = new javax.swing.JButton();
        txt_nombrebuscar = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        lbla = new javax.swing.JLabel();
        btn_verEstud = new javax.swing.JButton();

        btn_salir1.setText("Ver Estudiantes");
        btn_salir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salir1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_agregar.setText("Agregar");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        list_cursos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(list_cursos);

        btn_verProfesor.setText("Ver Profesores");
        btn_verProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verProfesorActionPerformed(evt);
            }
        });

        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        lbla.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbla.setText("Gestor de Cursos");

        btn_verEstud.setText("Ver Estudiantes");
        btn_verEstud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verEstudActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(lbla))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(txt_nombrebuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_buscar))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btn_verProfesor)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn_verEstud)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn_agregar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btn_eliminar))))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbla)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nombrebuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_agregar)
                    .addComponent(btn_eliminar)
                    .addComponent(btn_verProfesor)
                    .addComponent(btn_verEstud))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void llenarList(){
        DefaultListModel modelo =new DefaultListModel();        
        list_cursos.setModel(modelo); 
        modelo.removeAllElements();
        for (int i = 0; i < ListaCurso.size(); i++) {
            modelo.addElement(ListaCurso.get(i).getCodigo()+"         "+
            ListaCurso.get(i).getNombre()+"          "
            +ListaCurso.get(i).getCreditos());
        }
    }
    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
       
        PantallaEditarCurso pantaEditCurs =new PantallaEditarCurso(ListaCurso);
        pantaEditCurs.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btn_agregarActionPerformed
    private static Curso curso = null;
    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        String nombrCurso = txt_nombrebuscar.getText();
        boolean eliminado = false;
        if(!nombrCurso.isEmpty())
        {
            for (int i = 0; i < ListaCurso.size(); i++) {
                if(ListaCurso.get(i).getNombre().equals(nombrCurso))
                {
                    ListaCurso.remove(i);
                    eliminado= true;
                    llenarList();
                    JOptionPane.showMessageDialog(null, "Curso Eliminado",
                    "Eliminar", JOptionPane.INFORMATION_MESSAGE); 
                }
            }
            if(eliminado==false){
                 JOptionPane.showMessageDialog(null, "El curso ingresado no"
                         + " existe","Eliminar", JOptionPane.INFORMATION_MESSAGE); 
            }
        }else{
            JOptionPane.showMessageDialog(null, "Ingrese nombre del curso",
                    "Eliminar", JOptionPane.INFORMATION_MESSAGE);   
        }
        
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_verProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verProfesorActionPerformed
        // TODO add your handling code here:
        
        if(this.curso!=null)
        {
            PantallaProfesores pantaVerProfe = new PantallaProfesores(this.curso);
            pantaVerProfe.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Primero debe buscar el curso",
                    "Ver Profesores", JOptionPane.INFORMATION_MESSAGE);   
        }
        
    }//GEN-LAST:event_btn_verProfesorActionPerformed

    private void btn_salir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salir1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_salir1ActionPerformed

    private void btn_verEstudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verEstudActionPerformed
        if(this.curso!=null)
        {
            PantallaEstudiantes pantaVerEstu = new PantallaEstudiantes(this.curso);
            pantaVerEstu.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Primero debe buscar el curso",
                    "Ver Profesores", JOptionPane.INFORMATION_MESSAGE);   
        }
        
    }//GEN-LAST:event_btn_verEstudActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        // TODO add your handling code here:
        String nombrCurso = txt_nombrebuscar.getText();
        boolean encontrado = false;
        if(!nombrCurso.isEmpty())
        {
            for (int i = 0; i < ListaCurso.size(); i++) {
                if(ListaCurso.get(i).getNombre().equals(nombrCurso))
                {
                    encontrado= true;
                    llenarList();
                    this.curso=ListaCurso.get(i);
                    JOptionPane.showMessageDialog(null, "Curso Encontrado \n"
                        + "Codigo: "+ListaCurso.get(i).getCodigo()+"\n"
                        + "Nombre: "+ListaCurso.get(i).getNombre()+"\n"
                        + "Creditos: "+ListaCurso.get(i).getCreditos(),
                    "Eliminar", JOptionPane.INFORMATION_MESSAGE); 
                }
            }
            if(encontrado==false){
                 JOptionPane.showMessageDialog(null, "El curso ingresado no"
                         + " existe","Buscar", JOptionPane.INFORMATION_MESSAGE); 
            }
        }else{
            JOptionPane.showMessageDialog(null, "Ingrese nombre del curso",
                    "Buscar", JOptionPane.INFORMATION_MESSAGE);   
        }
    }//GEN-LAST:event_btn_buscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaGestorCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaGestorCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaGestorCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaGestorCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaGestorCursos(ListaCurso).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_salir1;
    private javax.swing.JButton btn_verEstud;
    private javax.swing.JButton btn_verProfesor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbla;
    private javax.swing.JList<String> list_cursos;
    private javax.swing.JTextField txt_nombrebuscar;
    // End of variables declaration//GEN-END:variables
}
